// Стартовый набор данных базы (тикет 13): продукты + рецепты, достаточные для
// сборки недели. Чистый модуль без импортов — его используют и сид (prisma/seed.ts),
// и тест на правдоподобность КБЖУ (src/core/nutrition/recipe.test.ts).
//
// КБЖУ/клетчатка/натрий на 100 г — справочные значения каталога из
// research/products-ru.md. Это осознанно табличные, а не пересчитанные факторами
// Атуотера значения: kbju-master.md D1 прямо назначает USDA/РФ-таблицы основным
// источником состава продуктов на 100 г («USDA — основной источник значений на
// 100 г для наполнения каталога»), а формула энергии A1 рассчитана на USDA-
// конвенцию углеводов (включают клетчатку), тогда как в нашей таблице «У» уже без
// клетчатки — прямое применение A1 дало бы двойной вычет и занижение. Итог блюда
// собирается из этих значений линейно (см. /core/nutrition/recipe.ts).
// Цены — ориентир (тикет 01, ненадёжны). Полное наполнение — тикет 21.

export type Unit = "g" | "ml" | "pcs";
export type Allergen =
  | "milk"
  | "gluten"
  | "egg"
  | "fish"
  | "meat"
  | "poultry"
  | "nuts"
  | "soy";
export type Slot = "breakfast" | "lunch" | "dinner" | "snack";
export type DietTag = "vegetarian" | "vegan" | "pescatarian";
export type Equipment = "stove" | "oven" | "blender" | "multicooker" | "none";

export interface SeedIngredient {
  /** Стабильный ключ = id в БД (идемпотентность сида). */
  slug: string;
  name: string;
  group: string;
  unit: Unit;
  kcal: number;
  protein: number;
  fat: number;
  carb: number;
  fiber: number;
  /** натрий, мг на 100 г */
  sodium: number;
  packSize: number;
  pricePerPack: number;
  shelfLifeDays: number;
  /** Масса одной штуки, г — только для штучных (unit="pcs"); для г/мл не задаётся. */
  gramsPerPiece?: number;
  allergens: Allergen[];
}

export interface SeedRecipeItem {
  /** slug ингредиента из INGREDIENTS */
  ingredient: string;
  /** масса на всё блюдо, г (для мл — миллилитры) */
  grams: number;
}

export interface SeedRecipe {
  slug: string;
  name: string;
  steps: string[];
  timeMin: number;
  difficulty: number;
  servings: number;
  slots: Slot[];
  diet: DietTag[];
  equipment: Equipment[];
  items: SeedRecipeItem[];
}

const G = {
  cereal: "Крупы и макароны",
  dairy: "Молочные продукты",
  meat: "Мясо и птица",
  fish: "Рыба и морепродукты",
  veg: "Овощи",
  fruit: "Фрукты и ягоды",
  grocery: "Бакалея",
  egg: "Яйца",
  nuts: "Орехи и семечки",
  bread: "Хлеб и выпечка",
  beverage: "Напитки",
  canned: "Консервы",
  frozen: "Замороженное",
} as const;

export const INGREDIENTS: SeedIngredient[] = [
  // --- 1. Крупы и макароны ---
  { slug: "grechka", name: "Гречка ядрица", group: G.cereal, unit: "g", kcal: 343, protein: 12.6, fat: 3.3, carb: 62, fiber: 11, sodium: 3, packSize: 900, pricePerPack: 95, shelfLifeDays: 540, allergens: [] },
  { slug: "ris-kruglyy", name: "Рис круглозёрный", group: G.cereal, unit: "g", kcal: 344, protein: 7.0, fat: 1.0, carb: 76, fiber: 1.4, sodium: 2, packSize: 900, pricePerPack: 90, shelfLifeDays: 540, allergens: [] },
  { slug: "ris-dlinnozernyy", name: "Рис длиннозёрный", group: G.cereal, unit: "g", kcal: 345, protein: 7.5, fat: 1.0, carb: 77, fiber: 1.4, sodium: 2, packSize: 800, pricePerPack: 110, shelfLifeDays: 540, allergens: [] },
  { slug: "ris-buryy", name: "Рис бурый", group: G.cereal, unit: "g", kcal: 337, protein: 7.4, fat: 2.8, carb: 72, fiber: 3.5, sodium: 4, packSize: 500, pricePerPack: 130, shelfLifeDays: 365, allergens: [] },
  { slug: "psheno", name: "Пшено шлифованное", group: G.cereal, unit: "g", kcal: 348, protein: 11.5, fat: 3.3, carb: 66, fiber: 3.6, sodium: 3, packSize: 800, pricePerPack: 65, shelfLifeDays: 300, allergens: [] },
  { slug: "ovsyanka", name: "Овсяные хлопья «Геркулес»", group: G.cereal, unit: "g", kcal: 355, protein: 12.3, fat: 6.2, carb: 62, fiber: 6.0, sodium: 5, packSize: 500, pricePerPack: 75, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "ovsyanka-bystraya", name: "Овсяные хлопья быстрые", group: G.cereal, unit: "g", kcal: 360, protein: 11.0, fat: 7.0, carb: 66, fiber: 6.0, sodium: 5, packSize: 400, pricePerPack: 70, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "manka", name: "Манная крупа", group: G.cereal, unit: "g", kcal: 333, protein: 10.3, fat: 1.0, carb: 70, fiber: 3.6, sodium: 3, packSize: 800, pricePerPack: 60, shelfLifeDays: 240, allergens: ["gluten"] },
  { slug: "perlovka", name: "Перловая крупа", group: G.cereal, unit: "g", kcal: 320, protein: 9.3, fat: 1.1, carb: 67, fiber: 7.8, sodium: 4, packSize: 800, pricePerPack: 55, shelfLifeDays: 450, allergens: ["gluten"] },
  { slug: "yachka", name: "Ячневая крупа", group: G.cereal, unit: "g", kcal: 324, protein: 10.0, fat: 1.3, carb: 66, fiber: 8.1, sodium: 4, packSize: 800, pricePerPack: 55, shelfLifeDays: 450, allergens: ["gluten"] },
  { slug: "kukuruznaya-krupa", name: "Кукурузная крупа", group: G.cereal, unit: "g", kcal: 328, protein: 8.3, fat: 1.2, carb: 71, fiber: 4.8, sodium: 5, packSize: 700, pricePerPack: 60, shelfLifeDays: 300, allergens: [] },
  { slug: "bulgur", name: "Булгур", group: G.cereal, unit: "g", kcal: 342, protein: 12.3, fat: 1.3, carb: 76, fiber: 12, sodium: 8, packSize: 450, pricePerPack: 115, shelfLifeDays: 365, allergens: ["gluten"] },
  { slug: "kuskus", name: "Кускус", group: G.cereal, unit: "g", kcal: 376, protein: 12.8, fat: 0.6, carb: 77, fiber: 5.0, sodium: 10, packSize: 500, pricePerPack: 120, shelfLifeDays: 365, allergens: ["gluten"] },
  { slug: "kinoa", name: "Киноа", group: G.cereal, unit: "g", kcal: 368, protein: 14.1, fat: 6.1, carb: 57, fiber: 7.0, sodium: 5, packSize: 300, pricePerPack: 260, shelfLifeDays: 540, allergens: [] },
  { slug: "chechevica", name: "Чечевица сухая", group: G.cereal, unit: "g", kcal: 314, protein: 24.6, fat: 1.5, carb: 46, fiber: 11, sodium: 6, packSize: 450, pricePerPack: 95, shelfLifeDays: 540, allergens: [] },
  { slug: "goroh", name: "Горох колотый", group: G.cereal, unit: "g", kcal: 298, protein: 23.0, fat: 1.6, carb: 48, fiber: 11, sodium: 5, packSize: 800, pricePerPack: 70, shelfLifeDays: 450, allergens: [] },
  { slug: "fasol", name: "Фасоль сухая", group: G.cereal, unit: "g", kcal: 298, protein: 21.0, fat: 2.0, carb: 47, fiber: 12, sodium: 6, packSize: 500, pricePerPack: 110, shelfLifeDays: 540, allergens: [] },
  { slug: "spagetti", name: "Спагетти из тв. сортов", group: G.cereal, unit: "g", kcal: 350, protein: 12.0, fat: 1.4, carb: 71, fiber: 3.5, sodium: 5, packSize: 450, pricePerPack: 85, shelfLifeDays: 720, allergens: ["gluten"] },
  { slug: "makarony", name: "Макароны рожки", group: G.cereal, unit: "g", kcal: 344, protein: 11, fat: 1.3, carb: 70, fiber: 3.0, sodium: 5, packSize: 400, pricePerPack: 60, shelfLifeDays: 720, allergens: ["gluten"] },
  { slug: "vermishel", name: "Вермишель яичная", group: G.cereal, unit: "g", kcal: 368, protein: 12.5, fat: 3.0, carb: 71, fiber: 3.0, sodium: 6, packSize: 400, pricePerPack: 75, shelfLifeDays: 540, allergens: ["gluten", "egg"] },
  { slug: "soba", name: "Лапша гречневая (соба)", group: G.cereal, unit: "g", kcal: 348, protein: 14.0, fat: 0.7, carb: 70, fiber: 4.0, sodium: 60, packSize: 300, pricePerPack: 180, shelfLifeDays: 540, allergens: ["gluten"] },

  // --- 2. Молочные продукты ---
  { slug: "moloko", name: "Молоко 2.5%", group: G.dairy, unit: "ml", kcal: 52, protein: 2.9, fat: 2.5, carb: 4.7, fiber: 0, sodium: 43, packSize: 930, pricePerPack: 75, shelfLifeDays: 10, allergens: ["milk"] },
  { slug: "moloko32", name: "Молоко 3.2%", group: G.dairy, unit: "ml", kcal: 59, protein: 2.9, fat: 3.2, carb: 4.7, fiber: 0, sodium: 43, packSize: 930, pricePerPack: 80, shelfLifeDays: 10, allergens: ["milk"] },
  { slug: "moloko-ultra", name: "Молоко ультрапастер. 3.2%", group: G.dairy, unit: "ml", kcal: 60, protein: 3.0, fat: 3.2, carb: 4.7, fiber: 0, sodium: 45, packSize: 950, pricePerPack: 90, shelfLifeDays: 120, allergens: ["milk"] },
  { slug: "kefir25", name: "Кефир 2.5%", group: G.dairy, unit: "ml", kcal: 50, protein: 3.0, fat: 2.5, carb: 4.0, fiber: 0, sodium: 50, packSize: 900, pricePerPack: 75, shelfLifeDays: 14, allergens: ["milk"] },
  { slug: "kefir", name: "Кефир 1%", group: G.dairy, unit: "ml", kcal: 40, protein: 3.0, fat: 1.0, carb: 4.0, fiber: 0, sodium: 50, packSize: 900, pricePerPack: 70, shelfLifeDays: 14, allergens: ["milk"] },
  { slug: "ryazhenka", name: "Ряженка 4%", group: G.dairy, unit: "ml", kcal: 67, protein: 2.9, fat: 4.0, carb: 4.2, fiber: 0, sodium: 50, packSize: 450, pricePerPack: 65, shelfLifeDays: 14, allergens: ["milk"] },
  { slug: "tvorog5", name: "Творог 5%", group: G.dairy, unit: "g", kcal: 121, protein: 17.2, fat: 5.0, carb: 3.0, fiber: 0, sodium: 41, packSize: 200, pricePerPack: 90, shelfLifeDays: 10, allergens: ["milk"] },
  { slug: "tvorog9", name: "Творог 9%", group: G.dairy, unit: "g", kcal: 159, protein: 16.7, fat: 9.0, carb: 2.0, fiber: 0, sodium: 41, packSize: 200, pricePerPack: 95, shelfLifeDays: 10, allergens: ["milk"] },
  { slug: "tvorog-obezzh", name: "Творог обезжиренный", group: G.dairy, unit: "g", kcal: 71, protein: 18.0, fat: 0.6, carb: 1.8, fiber: 0, sodium: 44, packSize: 200, pricePerPack: 85, shelfLifeDays: 10, allergens: ["milk"] },
  { slug: "smetana", name: "Сметана 15%", group: G.dairy, unit: "g", kcal: 158, protein: 2.6, fat: 15.0, carb: 3.6, fiber: 0, sodium: 35, packSize: 315, pricePerPack: 90, shelfLifeDays: 14, allergens: ["milk"] },
  { slug: "smetana20", name: "Сметана 20%", group: G.dairy, unit: "g", kcal: 204, protein: 2.5, fat: 20.0, carb: 3.4, fiber: 0, sodium: 35, packSize: 315, pricePerPack: 105, shelfLifeDays: 14, allergens: ["milk"] },
  { slug: "yogurt", name: "Йогурт натуральный 3.2%", group: G.dairy, unit: "g", kcal: 66, protein: 5.0, fat: 3.2, carb: 3.5, fiber: 0, sodium: 50, packSize: 290, pricePerPack: 70, shelfLifeDays: 21, allergens: ["milk"] },
  { slug: "yogurt-pit", name: "Йогурт питьевой фруктовый", group: G.dairy, unit: "ml", kcal: 85, protein: 2.8, fat: 2.5, carb: 12.5, fiber: 0, sodium: 45, packSize: 290, pricePerPack: 60, shelfLifeDays: 21, allergens: ["milk"] },
  { slug: "syr", name: "Сыр «Российский» 50%", group: G.dairy, unit: "g", kcal: 363, protein: 23.0, fat: 29.5, carb: 0, fiber: 0, sodium: 820, packSize: 200, pricePerPack: 220, shelfLifeDays: 120, allergens: ["milk"] },
  { slug: "syr-plavlenyy", name: "Сыр плавленый", group: G.dairy, unit: "g", kcal: 290, protein: 12.0, fat: 24.0, carb: 5.0, fiber: 0, sodium: 1100, packSize: 180, pricePerPack: 120, shelfLifeDays: 120, allergens: ["milk"] },
  { slug: "syr-gauda", name: "Сыр «Гауда» полутвёрдый", group: G.dairy, unit: "g", kcal: 356, protein: 24.0, fat: 28.0, carb: 2.0, fiber: 0, sodium: 700, packSize: 200, pricePerPack: 250, shelfLifeDays: 120, allergens: ["milk"] },
  { slug: "mocarella", name: "Сыр моцарелла", group: G.dairy, unit: "g", kcal: 280, protein: 22.0, fat: 21.0, carb: 2.2, fiber: 0, sodium: 400, packSize: 125, pricePerPack: 130, shelfLifeDays: 30, allergens: ["milk"] },
  { slug: "syr-tvorozhnyy", name: "Сыр творожный (крем)", group: G.dairy, unit: "g", kcal: 253, protein: 6.0, fat: 24.0, carb: 3.5, fiber: 0, sodium: 400, packSize: 140, pricePerPack: 130, shelfLifeDays: 90, allergens: ["milk"] },
  { slug: "maslo-slivochnoe", name: "Масло сливочное 82.5%", group: G.dairy, unit: "g", kcal: 748, protein: 0.5, fat: 82.5, carb: 0.8, fiber: 0, sodium: 15, packSize: 180, pricePerPack: 195, shelfLifeDays: 120, allergens: ["milk"] },
  { slug: "slivki10", name: "Сливки 10%", group: G.dairy, unit: "ml", kcal: 118, protein: 3.0, fat: 10.0, carb: 4.0, fiber: 0, sodium: 40, packSize: 350, pricePerPack: 90, shelfLifeDays: 30, allergens: ["milk"] },
  { slug: "slivki33", name: "Сливки 33% (для взбивания)", group: G.dairy, unit: "ml", kcal: 322, protein: 2.2, fat: 33.0, carb: 3.0, fiber: 0, sodium: 35, packSize: 500, pricePerPack: 250, shelfLifeDays: 60, allergens: ["milk"] },
  { slug: "morozhenoe-plombir", name: "Мороженое пломбир", group: G.dairy, unit: "g", kcal: 227, protein: 3.5, fat: 15.0, carb: 20.5, fiber: 0, sodium: 60, packSize: 250, pricePerPack: 130, shelfLifeDays: 180, allergens: ["milk"] },

  // --- 3. Мясо и птица ---
  { slug: "kur-file", name: "Куриное филе грудки", group: G.meat, unit: "g", kcal: 113, protein: 23.5, fat: 1.9, carb: 0, fiber: 0, sodium: 60, packSize: 800, pricePerPack: 260, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "kur-bedro", name: "Куриное бедро (мякоть)", group: G.meat, unit: "g", kcal: 185, protein: 18.0, fat: 12.5, carb: 0, fiber: 0, sodium: 75, packSize: 900, pricePerPack: 230, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "kur-goleni", name: "Куриные голени", group: G.meat, unit: "g", kcal: 158, protein: 18.0, fat: 9.5, carb: 0, fiber: 0, sodium: 80, packSize: 900, pricePerPack: 210, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "kur-krylya", name: "Куриные крылья", group: G.meat, unit: "g", kcal: 186, protein: 19.0, fat: 12.2, carb: 0, fiber: 0, sodium: 80, packSize: 900, pricePerPack: 200, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "kur-tushka", name: "Тушка курицы (бройлер)", group: G.meat, unit: "g", kcal: 190, protein: 18.0, fat: 13.0, carb: 0, fiber: 0, sodium: 70, packSize: 1600, pricePerPack: 260, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "indeyka-file", name: "Филе индейки грудки", group: G.meat, unit: "g", kcal: 104, protein: 22.0, fat: 1.5, carb: 0, fiber: 0, sodium: 55, packSize: 700, pricePerPack: 340, shelfLifeDays: 6, allergens: ["poultry"] },
  { slug: "farsh-indeyka", name: "Фарш индейки", group: G.meat, unit: "g", kcal: 161, protein: 18.0, fat: 10.0, carb: 0, fiber: 0, sodium: 70, packSize: 400, pricePerPack: 220, shelfLifeDays: 5, allergens: ["poultry"] },
  { slug: "govyadina", name: "Говядина (лопатка)", group: G.meat, unit: "g", kcal: 187, protein: 19.0, fat: 12.0, carb: 0, fiber: 0, sodium: 65, packSize: 1000, pricePerPack: 550, shelfLifeDays: 5, allergens: ["meat"] },
  { slug: "govyadina-vyrezka", name: "Говядина вырезка", group: G.meat, unit: "g", kcal: 158, protein: 20.0, fat: 8.5, carb: 0, fiber: 0, sodium: 60, packSize: 500, pricePerPack: 500, shelfLifeDays: 5, allergens: ["meat"] },
  { slug: "farsh-govyazhiy", name: "Фарш говяжий", group: G.meat, unit: "g", kcal: 254, protein: 17.0, fat: 20.0, carb: 0, fiber: 0, sodium: 70, packSize: 500, pricePerPack: 320, shelfLifeDays: 3, allergens: ["meat"] },
  { slug: "svinina", name: "Свинина (лопатка)", group: G.meat, unit: "g", kcal: 257, protein: 16.0, fat: 21.0, carb: 0, fiber: 0, sodium: 60, packSize: 1000, pricePerPack: 350, shelfLifeDays: 5, allergens: ["meat"] },
  { slug: "svinina-karbonad", name: "Свинина карбонад/корейка", group: G.meat, unit: "g", kcal: 242, protein: 19.0, fat: 18.0, carb: 0, fiber: 0, sodium: 60, packSize: 800, pricePerPack: 380, shelfLifeDays: 5, allergens: ["meat"] },
  { slug: "farsh-svino-govyazhiy", name: "Фарш свино-говяжий", group: G.meat, unit: "g", kcal: 263, protein: 15.0, fat: 22.0, carb: 0, fiber: 0, sodium: 70, packSize: 500, pricePerPack: 300, shelfLifeDays: 3, allergens: ["meat"] },
  { slug: "sosiski", name: "Сосиски молочные", group: G.meat, unit: "g", kcal: 266, protein: 11.0, fat: 24.0, carb: 1.5, fiber: 0, sodium: 900, packSize: 450, pricePerPack: 210, shelfLifeDays: 20, allergens: ["meat", "milk"] },
  { slug: "sardelki", name: "Сардельки", group: G.meat, unit: "g", kcal: 250, protein: 10.0, fat: 22.0, carb: 2.0, fiber: 0, sodium: 950, packSize: 500, pricePerPack: 230, shelfLifeDays: 20, allergens: ["meat"] },
  { slug: "kolbasa-varenaya", name: "Колбаса варёная «Докторская»", group: G.meat, unit: "g", kcal: 257, protein: 13.0, fat: 22.0, carb: 1.5, fiber: 0, sodium: 900, packSize: 500, pricePerPack: 320, shelfLifeDays: 25, allergens: ["meat"] },
  { slug: "kolbasa-pk", name: "Колбаса п/копчёная", group: G.meat, unit: "g", kcal: 420, protein: 17.0, fat: 39.0, carb: 1.0, fiber: 0, sodium: 1200, packSize: 400, pricePerPack: 380, shelfLifeDays: 45, allergens: ["meat"] },
  { slug: "bekon", name: "Бекон / грудинка с/к", group: G.meat, unit: "g", kcal: 500, protein: 12.0, fat: 50.0, carb: 0, fiber: 0, sodium: 1300, packSize: 200, pricePerPack: 250, shelfLifeDays: 45, allergens: ["meat"] },
  { slug: "vetchina", name: "Ветчина", group: G.meat, unit: "g", kcal: 270, protein: 14.0, fat: 23.0, carb: 1.0, fiber: 0, sodium: 950, packSize: 300, pricePerPack: 260, shelfLifeDays: 30, allergens: ["meat"] },
  { slug: "pechen-kurinaya", name: "Печень куриная", group: G.meat, unit: "g", kcal: 137, protein: 19.0, fat: 6.3, carb: 0.7, fiber: 0, sodium: 80, packSize: 500, pricePerPack: 130, shelfLifeDays: 4, allergens: ["poultry"] },

  // --- 4. Рыба и морепродукты ---
  { slug: "mintay", name: "Минтай (филе)", group: G.fish, unit: "g", kcal: 72, protein: 16.0, fat: 0.9, carb: 0, fiber: 0, sodium: 70, packSize: 800, pricePerPack: 220, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "treska", name: "Треска", group: G.fish, unit: "g", kcal: 78, protein: 17.7, fat: 0.7, carb: 0, fiber: 0, sodium: 70, packSize: 600, pricePerPack: 350, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "gorbusha", name: "Горбуша", group: G.fish, unit: "g", kcal: 142, protein: 20.5, fat: 6.5, carb: 0, fiber: 0, sodium: 60, packSize: 1000, pricePerPack: 450, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "semga", name: "Сёмга (филе)", group: G.fish, unit: "g", kcal: 208, protein: 20.0, fat: 14.0, carb: 0, fiber: 0, sodium: 60, packSize: 400, pricePerPack: 700, shelfLifeDays: 10, allergens: ["fish"] },
  { slug: "forel", name: "Форель (филе)", group: G.fish, unit: "g", kcal: 141, protein: 20.5, fat: 6.0, carb: 0, fiber: 0, sodium: 55, packSize: 400, pricePerPack: 620, shelfLifeDays: 10, allergens: ["fish"] },
  { slug: "skumbriya", name: "Скумбрия", group: G.fish, unit: "g", kcal: 191, protein: 18.0, fat: 13.2, carb: 0, fiber: 0, sodium: 90, packSize: 700, pricePerPack: 280, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "seld-solenaya", name: "Сельдь солёная", group: G.fish, unit: "g", kcal: 217, protein: 17.0, fat: 16.5, carb: 0, fiber: 0, sodium: 700, packSize: 400, pricePerPack: 200, shelfLifeDays: 30, allergens: ["fish"] },
  { slug: "hek", name: "Хек", group: G.fish, unit: "g", kcal: 86, protein: 16.6, fat: 2.2, carb: 0, fiber: 0, sodium: 70, packSize: 800, pricePerPack: 260, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "tilapiya", name: "Тилапия (филе)", group: G.fish, unit: "g", kcal: 96, protein: 20.0, fat: 1.7, carb: 0, fiber: 0, sodium: 55, packSize: 600, pricePerPack: 300, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "putassu", name: "Путассу", group: G.fish, unit: "g", kcal: 82, protein: 18.5, fat: 0.9, carb: 0, fiber: 0, sodium: 70, packSize: 800, pricePerPack: 160, shelfLifeDays: 180, allergens: ["fish"] },
  { slug: "moyva", name: "Мойва", group: G.fish, unit: "g", kcal: 217, protein: 13.0, fat: 18.0, carb: 0, fiber: 0, sodium: 90, packSize: 500, pricePerPack: 150, shelfLifeDays: 120, allergens: ["fish"] },
  { slug: "krevetki", name: "Креветки варёно-мороженые", group: G.fish, unit: "g", kcal: 95, protein: 18.9, fat: 2.2, carb: 0, fiber: 0, sodium: 150, packSize: 500, pricePerPack: 400, shelfLifeDays: 180, allergens: [] },
  { slug: "kalmar", name: "Кальмар (тушка мороженая)", group: G.fish, unit: "g", kcal: 92, protein: 18.0, fat: 2.2, carb: 2.0, fiber: 0, sodium: 110, packSize: 500, pricePerPack: 300, shelfLifeDays: 180, allergens: [] },
  { slug: "midii", name: "Мидии варёно-мороженые", group: G.fish, unit: "g", kcal: 77, protein: 11.5, fat: 2.0, carb: 3.3, fiber: 0, sodium: 290, packSize: 300, pricePerPack: 280, shelfLifeDays: 180, allergens: [] },
  { slug: "ikra-mintaya", name: "Икра минтая / трески", group: G.fish, unit: "g", kcal: 132, protein: 27.0, fat: 1.8, carb: 1.0, fiber: 0, sodium: 600, packSize: 130, pricePerPack: 200, shelfLifeDays: 90, allergens: ["fish"] },

  // --- 5. Овощи ---
  { slug: "kartofel", name: "Картофель", group: G.veg, unit: "g", kcal: 77, protein: 2.0, fat: 0.4, carb: 16.0, fiber: 1.4, sodium: 6, packSize: 2500, pricePerPack: 100, shelfLifeDays: 60, allergens: [] },
  { slug: "morkov", name: "Морковь", group: G.veg, unit: "g", kcal: 35, protein: 1.3, fat: 0.1, carb: 6.9, fiber: 2.4, sodium: 60, packSize: 1000, pricePerPack: 50, shelfLifeDays: 60, allergens: [] },
  { slug: "luk", name: "Лук репчатый", group: G.veg, unit: "g", kcal: 41, protein: 1.4, fat: 0.2, carb: 8.2, fiber: 1.7, sodium: 4, packSize: 1000, pricePerPack: 45, shelfLifeDays: 90, allergens: [] },
  { slug: "kapusta", name: "Капуста белокочанная", group: G.veg, unit: "g", kcal: 28, protein: 1.8, fat: 0.1, carb: 4.7, fiber: 2.0, sodium: 18, packSize: 1000, pricePerPack: 40, shelfLifeDays: 60, allergens: [] },
  { slug: "kapusta-cvetnaya", name: "Капуста цветная", group: G.veg, unit: "g", kcal: 30, protein: 2.5, fat: 0.3, carb: 4.2, fiber: 2.1, sodium: 15, packSize: 600, pricePerPack: 90, shelfLifeDays: 14, allergens: [] },
  { slug: "brokkoli", name: "Брокколи", group: G.veg, unit: "g", kcal: 34, protein: 2.8, fat: 0.4, carb: 4.0, fiber: 2.6, sodium: 30, packSize: 400, pricePerPack: 130, shelfLifeDays: 10, allergens: [] },
  { slug: "pomidory", name: "Помидоры", group: G.veg, unit: "g", kcal: 20, protein: 1.1, fat: 0.2, carb: 3.7, fiber: 1.2, sodium: 5, packSize: 1000, pricePerPack: 180, shelfLifeDays: 10, allergens: [] },
  { slug: "ogurcy", name: "Огурцы", group: G.veg, unit: "g", kcal: 15, protein: 0.8, fat: 0.1, carb: 2.8, fiber: 0.7, sodium: 2, packSize: 1000, pricePerPack: 130, shelfLifeDays: 10, allergens: [] },
  { slug: "perec", name: "Перец болгарский", group: G.veg, unit: "g", kcal: 27, protein: 1.3, fat: 0.1, carb: 5.3, fiber: 1.9, sodium: 3, packSize: 500, pricePerPack: 150, shelfLifeDays: 12, allergens: [] },
  { slug: "svekla", name: "Свёкла", group: G.veg, unit: "g", kcal: 43, protein: 1.5, fat: 0.1, carb: 8.8, fiber: 2.8, sodium: 78, packSize: 1000, pricePerPack: 45, shelfLifeDays: 60, allergens: [] },
  { slug: "kabachok", name: "Кабачок", group: G.veg, unit: "g", kcal: 24, protein: 0.6, fat: 0.3, carb: 4.6, fiber: 1.0, sodium: 3, packSize: 700, pricePerPack: 90, shelfLifeDays: 21, allergens: [] },
  { slug: "baklazhan", name: "Баклажан", group: G.veg, unit: "g", kcal: 24, protein: 1.2, fat: 0.1, carb: 4.5, fiber: 3.0, sodium: 2, packSize: 500, pricePerPack: 120, shelfLifeDays: 14, allergens: [] },
  { slug: "tykva", name: "Тыква", group: G.veg, unit: "g", kcal: 26, protein: 1.0, fat: 0.1, carb: 4.4, fiber: 2.1, sodium: 1, packSize: 1500, pricePerPack: 90, shelfLifeDays: 60, allergens: [] },
  { slug: "chesnok", name: "Чеснок", group: G.veg, unit: "g", kcal: 143, protein: 6.5, fat: 0.5, carb: 30.0, fiber: 1.5, sodium: 17, packSize: 200, pricePerPack: 90, shelfLifeDays: 90, allergens: [] },
  { slug: "shampinony", name: "Шампиньоны", group: G.veg, unit: "g", kcal: 22, protein: 3.1, fat: 0.3, carb: 3.3, fiber: 1.0, sodium: 5, packSize: 400, pricePerPack: 120, shelfLifeDays: 7, allergens: [] },
  { slug: "salat", name: "Салат листовой", group: G.veg, unit: "g", kcal: 15, protein: 1.4, fat: 0.2, carb: 2.9, fiber: 1.3, sodium: 28, packSize: 150, pricePerPack: 90, shelfLifeDays: 7, allergens: [] },
  { slug: "shpinat", name: "Шпинат", group: G.veg, unit: "g", kcal: 23, protein: 2.9, fat: 0.4, carb: 3.6, fiber: 2.2, sodium: 79, packSize: 200, pricePerPack: 130, shelfLifeDays: 7, allergens: [] },
  { slug: "zelen", name: "Зелень (укроп/петрушка)", group: G.veg, unit: "g", kcal: 43, protein: 3.5, fat: 0.5, carb: 6.3, fiber: 3.0, sodium: 40, packSize: 100, pricePerPack: 60, shelfLifeDays: 7, allergens: [] },
  { slug: "kukuruza-pochatok", name: "Кукуруза початок", group: G.veg, unit: "g", kcal: 96, protein: 3.4, fat: 1.5, carb: 19.0, fiber: 2.7, sodium: 15, packSize: 500, pricePerPack: 90, shelfLifeDays: 10, allergens: [] },
  { slug: "redis", name: "Редис", group: G.veg, unit: "g", kcal: 20, protein: 1.2, fat: 0.1, carb: 3.4, fiber: 1.6, sodium: 39, packSize: 300, pricePerPack: 90, shelfLifeDays: 10, allergens: [] },
  { slug: "selderey", name: "Сельдерей (черешки)", group: G.veg, unit: "g", kcal: 16, protein: 0.9, fat: 0.2, carb: 3.0, fiber: 1.8, sodium: 80, packSize: 300, pricePerPack: 130, shelfLifeDays: 14, allergens: [] },

  // --- 6. Фрукты и ягоды ---
  { slug: "yabloki", name: "Яблоки", group: G.fruit, unit: "g", kcal: 47, protein: 0.4, fat: 0.4, carb: 9.8, fiber: 2.4, sodium: 1, packSize: 1000, pricePerPack: 110, shelfLifeDays: 30, allergens: [] },
  { slug: "banany", name: "Бананы", group: G.fruit, unit: "g", kcal: 96, protein: 1.5, fat: 0.5, carb: 21.0, fiber: 1.7, sodium: 1, packSize: 1000, pricePerPack: 100, shelfLifeDays: 7, allergens: [] },
  { slug: "apelsiny", name: "Апельсины", group: G.fruit, unit: "g", kcal: 43, protein: 0.9, fat: 0.2, carb: 8.1, fiber: 2.2, sodium: 0, packSize: 1000, pricePerPack: 130, shelfLifeDays: 21, allergens: [] },
  { slug: "mandariny", name: "Мандарины", group: G.fruit, unit: "g", kcal: 38, protein: 0.8, fat: 0.2, carb: 7.5, fiber: 1.9, sodium: 1, packSize: 1000, pricePerPack: 150, shelfLifeDays: 14, allergens: [] },
  { slug: "grushi", name: "Груши", group: G.fruit, unit: "g", kcal: 47, protein: 0.4, fat: 0.3, carb: 10.3, fiber: 2.9, sodium: 1, packSize: 1000, pricePerPack: 140, shelfLifeDays: 21, allergens: [] },
  { slug: "limony", name: "Лимоны", group: G.fruit, unit: "g", kcal: 34, protein: 0.9, fat: 0.1, carb: 3.0, fiber: 2.0, sodium: 2, packSize: 500, pricePerPack: 120, shelfLifeDays: 30, allergens: [] },
  { slug: "vinograd", name: "Виноград", group: G.fruit, unit: "g", kcal: 72, protein: 0.6, fat: 0.2, carb: 15.4, fiber: 0.9, sodium: 2, packSize: 500, pricePerPack: 180, shelfLifeDays: 10, allergens: [] },
  { slug: "greypfrut", name: "Грейпфрут", group: G.fruit, unit: "g", kcal: 35, protein: 0.7, fat: 0.2, carb: 6.5, fiber: 1.8, sodium: 0, packSize: 500, pricePerPack: 130, shelfLifeDays: 21, allergens: [] },
  { slug: "kivi", name: "Киви", group: G.fruit, unit: "g", kcal: 47, protein: 1.0, fat: 0.6, carb: 8.1, fiber: 3.0, sodium: 3, packSize: 500, pricePerPack: 150, shelfLifeDays: 14, allergens: [] },
  { slug: "ananas", name: "Ананас", group: G.fruit, unit: "g", kcal: 49, protein: 0.4, fat: 0.2, carb: 10.6, fiber: 1.2, sodium: 1, packSize: 1200, pricePerPack: 200, shelfLifeDays: 7, allergens: [] },
  { slug: "avokado", name: "Авокадо", group: G.fruit, unit: "g", kcal: 160, protein: 2.0, fat: 14.7, carb: 1.8, fiber: 6.7, sodium: 7, packSize: 300, pricePerPack: 200, shelfLifeDays: 7, allergens: [] },
  { slug: "hurma", name: "Хурма", group: G.fruit, unit: "g", kcal: 67, protein: 0.5, fat: 0.4, carb: 15.3, fiber: 3.6, sodium: 1, packSize: 1000, pricePerPack: 180, shelfLifeDays: 10, allergens: [] },
  { slug: "klubnika", name: "Клубника", group: G.fruit, unit: "g", kcal: 32, protein: 0.7, fat: 0.3, carb: 7.5, fiber: 2.0, sodium: 1, packSize: 500, pricePerPack: 250, shelfLifeDays: 5, allergens: [] },
  { slug: "chernika", name: "Черника", group: G.fruit, unit: "g", kcal: 44, protein: 0.7, fat: 0.5, carb: 7.6, fiber: 2.4, sodium: 1, packSize: 300, pricePerPack: 200, shelfLifeDays: 5, allergens: [] },
  { slug: "malina", name: "Малина", group: G.fruit, unit: "g", kcal: 46, protein: 0.8, fat: 0.5, carb: 8.3, fiber: 3.7, sodium: 1, packSize: 250, pricePerPack: 180, shelfLifeDays: 3, allergens: [] },
  { slug: "smorodina", name: "Смородина чёрная", group: G.fruit, unit: "g", kcal: 44, protein: 1.0, fat: 0.4, carb: 7.3, fiber: 4.8, sodium: 2, packSize: 300, pricePerPack: 150, shelfLifeDays: 5, allergens: [] },
  { slug: "vishnya", name: "Вишня", group: G.fruit, unit: "g", kcal: 52, protein: 0.8, fat: 0.2, carb: 10.6, fiber: 1.8, sodium: 3, packSize: 1000, pricePerPack: 200, shelfLifeDays: 5, allergens: [] },
  { slug: "sliva", name: "Слива", group: G.fruit, unit: "g", kcal: 42, protein: 0.8, fat: 0.3, carb: 9.6, fiber: 1.5, sodium: 2, packSize: 1000, pricePerPack: 150, shelfLifeDays: 14, allergens: [] },
  { slug: "persiki", name: "Персики", group: G.fruit, unit: "g", kcal: 45, protein: 0.9, fat: 0.1, carb: 9.5, fiber: 1.5, sodium: 1, packSize: 1000, pricePerPack: 180, shelfLifeDays: 7, allergens: [] },
  { slug: "arbuz", name: "Арбуз", group: G.fruit, unit: "g", kcal: 27, protein: 0.6, fat: 0.1, carb: 5.8, fiber: 0.4, sodium: 1, packSize: 5000, pricePerPack: 250, shelfLifeDays: 14, allergens: [] },

  // --- 7. Бакалея ---
  { slug: "muka", name: "Мука пшеничная в/с", group: G.grocery, unit: "g", kcal: 342, protein: 10.3, fat: 1.1, carb: 70.6, fiber: 3.5, sodium: 2, packSize: 2000, pricePerPack: 90, shelfLifeDays: 365, allergens: ["gluten"] },
  { slug: "muka-cz", name: "Мука цельнозерновая", group: G.grocery, unit: "g", kcal: 298, protein: 11.5, fat: 2.2, carb: 56.0, fiber: 10.7, sodium: 3, packSize: 1000, pricePerPack: 90, shelfLifeDays: 300, allergens: ["gluten"] },
  { slug: "muka-rzhanaya", name: "Мука ржаная", group: G.grocery, unit: "g", kcal: 298, protein: 8.9, fat: 1.7, carb: 61.8, fiber: 12.4, sodium: 2, packSize: 1000, pricePerPack: 70, shelfLifeDays: 300, allergens: ["gluten"] },
  { slug: "sahar", name: "Сахар-песок", group: G.grocery, unit: "g", kcal: 399, protein: 0, fat: 0, carb: 99.8, fiber: 0, sodium: 1, packSize: 900, pricePerPack: 75, shelfLifeDays: 720, allergens: [] },
  { slug: "sahar-pudra", name: "Сахарная пудра", group: G.grocery, unit: "g", kcal: 400, protein: 0, fat: 0, carb: 99.8, fiber: 0, sodium: 1, packSize: 200, pricePerPack: 60, shelfLifeDays: 720, allergens: [] },
  { slug: "sol", name: "Соль поваренная", group: G.grocery, unit: "g", kcal: 0, protein: 0, fat: 0, carb: 0, fiber: 0, sodium: 38700, packSize: 1000, pricePerPack: 25, shelfLifeDays: 1800, allergens: [] },
  { slug: "maslo-podsolnechnoe", name: "Масло подсолнечное", group: G.grocery, unit: "ml", kcal: 899, protein: 0, fat: 99.9, carb: 0, fiber: 0, sodium: 0, packSize: 1000, pricePerPack: 120, shelfLifeDays: 540, allergens: [] },
  { slug: "maslo-olivkovoe", name: "Масло оливковое", group: G.grocery, unit: "ml", kcal: 898, protein: 0, fat: 99.8, carb: 0, fiber: 0, sodium: 2, packSize: 500, pricePerPack: 500, shelfLifeDays: 540, allergens: [] },
  { slug: "med", name: "Мёд натуральный", group: G.grocery, unit: "g", kcal: 329, protein: 0.8, fat: 0, carb: 81.5, fiber: 0.2, sodium: 4, packSize: 500, pricePerPack: 350, shelfLifeDays: 730, allergens: [] },
  { slug: "uksus", name: "Уксус столовый 9%", group: G.grocery, unit: "ml", kcal: 11, protein: 0, fat: 0, carb: 3.0, fiber: 0, sodium: 5, packSize: 500, pricePerPack: 40, shelfLifeDays: 540, allergens: [] },
  { slug: "ketchup", name: "Кетчуп томатный", group: G.grocery, unit: "g", kcal: 99, protein: 1.8, fat: 0.5, carb: 22.0, fiber: 1.5, sodium: 900, packSize: 350, pricePerPack: 90, shelfLifeDays: 180, allergens: [] },
  { slug: "mayonez", name: "Майонез 67%", group: G.grocery, unit: "g", kcal: 620, protein: 1.0, fat: 67.0, carb: 2.6, fiber: 0, sodium: 500, packSize: 400, pricePerPack: 130, shelfLifeDays: 90, allergens: ["egg"] },
  { slug: "soevyy-sous", name: "Соус соевый", group: G.grocery, unit: "ml", kcal: 55, protein: 6.0, fat: 0, carb: 7.0, fiber: 0, sodium: 5500, packSize: 250, pricePerPack: 130, shelfLifeDays: 720, allergens: ["gluten", "soy"] },
  { slug: "gorchica", name: "Горчица столовая", group: G.grocery, unit: "g", kcal: 143, protein: 6.0, fat: 8.0, carb: 12.0, fiber: 3.0, sodium: 1200, packSize: 180, pricePerPack: 60, shelfLifeDays: 180, allergens: [] },
  { slug: "tomat-pasta", name: "Томатная паста", group: G.grocery, unit: "g", kcal: 92, protein: 4.3, fat: 0.5, carb: 19.0, fiber: 3.5, sodium: 40, packSize: 500, pricePerPack: 100, shelfLifeDays: 360, allergens: [] },
  { slug: "drozhzhi", name: "Дрожжи сухие", group: G.grocery, unit: "g", kcal: 325, protein: 40.0, fat: 6.0, carb: 30.0, fiber: 27, sodium: 50, packSize: 100, pricePerPack: 90, shelfLifeDays: 540, allergens: [] },
  { slug: "razryhlitel", name: "Разрыхлитель теста", group: G.grocery, unit: "g", kcal: 79, protein: 0, fat: 0, carb: 20.0, fiber: 0, sodium: 8000, packSize: 100, pricePerPack: 40, shelfLifeDays: 540, allergens: [] },
  { slug: "kakao-poroshok", name: "Какао-порошок", group: G.grocery, unit: "g", kcal: 289, protein: 24.0, fat: 15.0, carb: 10.0, fiber: 33, sodium: 20, packSize: 100, pricePerPack: 120, shelfLifeDays: 540, allergens: [] },
  { slug: "krahmal", name: "Крахмал картофельный", group: G.grocery, unit: "g", kcal: 300, protein: 0.1, fat: 0, carb: 79.0, fiber: 0, sodium: 6, packSize: 200, pricePerPack: 45, shelfLifeDays: 540, allergens: [] },
  { slug: "vanilnyy-sahar", name: "Ванильный сахар", group: G.grocery, unit: "g", kcal: 398, protein: 0, fat: 0, carb: 99.0, fiber: 0, sodium: 1, packSize: 20, pricePerPack: 15, shelfLifeDays: 540, allergens: [] },

  // --- 8. Яйца ---
  { slug: "yaytso", name: "Яйцо куриное С1", group: G.egg, unit: "pcs", kcal: 157, protein: 12.7, fat: 11.5, carb: 0.7, fiber: 0, sodium: 134, packSize: 10, pricePerPack: 110, shelfLifeDays: 25, gramsPerPiece: 55, allergens: ["egg"] },
  { slug: "yaytso-c0", name: "Яйцо куриное С0 (отборное)", group: G.egg, unit: "pcs", kcal: 157, protein: 12.7, fat: 11.5, carb: 0.7, fiber: 0, sodium: 134, packSize: 10, pricePerPack: 120, shelfLifeDays: 25, gramsPerPiece: 65, allergens: ["egg"] },
  { slug: "yaytso-perepelinoe", name: "Яйцо перепелиное", group: G.egg, unit: "pcs", kcal: 168, protein: 11.9, fat: 13.1, carb: 0.6, fiber: 0, sodium: 115, packSize: 20, pricePerPack: 95, shelfLifeDays: 30, gramsPerPiece: 12, allergens: ["egg"] },
  { slug: "belok-pasterizovannyy", name: "Меланж / белок пастер.", group: G.egg, unit: "ml", kcal: 44, protein: 11.0, fat: 0.2, carb: 0.7, fiber: 0, sodium: 160, packSize: 500, pricePerPack: 150, shelfLifeDays: 30, allergens: ["egg"] },

  // --- 9. Орехи и семечки ---
  { slug: "greckiy-orekh", name: "Грецкий орех (ядро)", group: G.nuts, unit: "g", kcal: 654, protein: 15.2, fat: 65.2, carb: 7.0, fiber: 6.7, sodium: 2, packSize: 150, pricePerPack: 200, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "mindal", name: "Миндаль", group: G.nuts, unit: "g", kcal: 609, protein: 18.6, fat: 53.7, carb: 13.0, fiber: 12.3, sodium: 1, packSize: 150, pricePerPack: 250, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "funduk", name: "Фундук", group: G.nuts, unit: "g", kcal: 651, protein: 15.0, fat: 61.5, carb: 9.4, fiber: 9.7, sodium: 0, packSize: 150, pricePerPack: 260, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "keshyu", name: "Кешью", group: G.nuts, unit: "g", kcal: 600, protein: 18.5, fat: 48.5, carb: 22.5, fiber: 3.3, sodium: 12, packSize: 150, pricePerPack: 240, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "arahis", name: "Арахис", group: G.nuts, unit: "g", kcal: 567, protein: 26.0, fat: 45.2, carb: 9.9, fiber: 8.5, sodium: 18, packSize: 200, pricePerPack: 130, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "fistashki", name: "Фисташки", group: G.nuts, unit: "g", kcal: 560, protein: 20.0, fat: 45.0, carb: 28.0, fiber: 10, sodium: 5, packSize: 150, pricePerPack: 300, shelfLifeDays: 180, allergens: ["nuts"] },
  { slug: "kedrovyy-orekh", name: "Кедровый орех", group: G.nuts, unit: "g", kcal: 673, protein: 13.7, fat: 68.4, carb: 13.1, fiber: 3.7, sodium: 2, packSize: 100, pricePerPack: 400, shelfLifeDays: 120, allergens: ["nuts"] },
  { slug: "semechki", name: "Семечки подсолнечника", group: G.nuts, unit: "g", kcal: 601, protein: 20.7, fat: 52.9, carb: 10.5, fiber: 8.6, sodium: 3, packSize: 200, pricePerPack: 90, shelfLifeDays: 180, allergens: [] },
  { slug: "semena-tykvy", name: "Семена тыквы", group: G.nuts, unit: "g", kcal: 559, protein: 24.5, fat: 45.8, carb: 4.7, fiber: 6.0, sodium: 7, packSize: 150, pricePerPack: 180, shelfLifeDays: 180, allergens: [] },
  { slug: "semena-lna", name: "Семена льна", group: G.nuts, unit: "g", kcal: 534, protein: 18.3, fat: 42.2, carb: 1.6, fiber: 27, sodium: 30, packSize: 200, pricePerPack: 100, shelfLifeDays: 365, allergens: [] },
  { slug: "kunzhut", name: "Кунжут", group: G.nuts, unit: "g", kcal: 573, protein: 17.7, fat: 49.7, carb: 12.2, fiber: 11.8, sodium: 11, packSize: 150, pricePerPack: 90, shelfLifeDays: 365, allergens: [] },
  { slug: "arahisovaya-pasta", name: "Арахисовая паста", group: G.nuts, unit: "g", kcal: 588, protein: 25.0, fat: 50.0, carb: 20.0, fiber: 6.0, sodium: 350, packSize: 340, pricePerPack: 320, shelfLifeDays: 270, allergens: ["nuts"] },

  // --- 10. Хлеб и выпечка ---
  { slug: "hleb-pshenichnyy", name: "Хлеб пшеничный (батон)", group: G.bread, unit: "g", kcal: 262, protein: 8.0, fat: 3.0, carb: 51.0, fiber: 2.5, sodium: 470, packSize: 400, pricePerPack: 45, shelfLifeDays: 4, allergens: ["gluten"] },
  { slug: "hleb-rzhanoy", name: "Хлеб ржаной «Дарницкий»", group: G.bread, unit: "g", kcal: 206, protein: 6.6, fat: 1.1, carb: 41.0, fiber: 5.8, sodium: 430, packSize: 700, pricePerPack: 55, shelfLifeDays: 5, allergens: ["gluten"] },
  { slug: "hleb-cz", name: "Хлеб цельнозерновой", group: G.bread, unit: "g", kcal: 229, protein: 8.5, fat: 3.5, carb: 40.0, fiber: 6.5, sodium: 400, packSize: 400, pricePerPack: 70, shelfLifeDays: 6, allergens: ["gluten"] },
  { slug: "hleb-bezdrozhzhevoy", name: "Хлеб бездрожжевой", group: G.bread, unit: "g", kcal: 235, protein: 7.5, fat: 2.5, carb: 46.0, fiber: 4.0, sodium: 420, packSize: 300, pricePerPack: 90, shelfLifeDays: 7, allergens: ["gluten"] },
  { slug: "baton", name: "Батон нарезной", group: G.bread, unit: "g", kcal: 264, protein: 7.5, fat: 2.9, carb: 51.4, fiber: 2.3, sodium: 480, packSize: 400, pricePerPack: 50, shelfLifeDays: 3, allergens: ["gluten"] },
  { slug: "lavash", name: "Лаваш тонкий", group: G.bread, unit: "g", kcal: 236, protein: 7.9, fat: 1.0, carb: 47.6, fiber: 1.8, sodium: 480, packSize: 200, pricePerPack: 40, shelfLifeDays: 7, allergens: ["gluten"] },
  { slug: "bulochka", name: "Булочка сдобная", group: G.bread, unit: "g", kcal: 339, protein: 7.6, fat: 9.4, carb: 55.5, fiber: 1.5, sodium: 380, packSize: 80, pricePerPack: 30, shelfLifeDays: 3, allergens: ["gluten", "egg", "milk"] },
  { slug: "suhari", name: "Сухари панировочные", group: G.bread, unit: "g", kcal: 347, protein: 11.0, fat: 2.0, carb: 71.0, fiber: 4.0, sodium: 550, packSize: 300, pricePerPack: 45, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "hlebcy", name: "Хлебцы ржаные", group: G.bread, unit: "g", kcal: 360, protein: 11.0, fat: 2.5, carb: 70.0, fiber: 16, sodium: 350, packSize: 100, pricePerPack: 70, shelfLifeDays: 300, allergens: ["gluten"] },
  { slug: "pechenye-ovsyanoe", name: "Печенье овсяное", group: G.bread, unit: "g", kcal: 437, protein: 6.5, fat: 14.5, carb: 71.0, fiber: 3.0, sodium: 250, packSize: 400, pricePerPack: 90, shelfLifeDays: 180, allergens: ["gluten", "egg"] },
  { slug: "pechenye-yubileynoe", name: "Печенье «Юбилейное»", group: G.bread, unit: "g", kcal: 445, protein: 7.0, fat: 13.0, carb: 74.0, fiber: 2.0, sodium: 300, packSize: 300, pricePerPack: 90, shelfLifeDays: 180, allergens: ["gluten", "egg", "milk"] },
  { slug: "krekery", name: "Крекеры солёные", group: G.bread, unit: "g", kcal: 430, protein: 9.0, fat: 12.0, carb: 71.0, fiber: 2.5, sodium: 900, packSize: 200, pricePerPack: 70, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "pryaniki", name: "Пряники", group: G.bread, unit: "g", kcal: 350, protein: 4.8, fat: 2.8, carb: 77.0, fiber: 1.5, sodium: 200, packSize: 350, pricePerPack: 90, shelfLifeDays: 90, allergens: ["gluten", "egg"] },
  { slug: "vafli", name: "Вафли", group: G.bread, unit: "g", kcal: 425, protein: 5.0, fat: 12.0, carb: 74.0, fiber: 1.0, sodium: 150, packSize: 220, pricePerPack: 80, shelfLifeDays: 120, allergens: ["gluten", "egg", "milk"] },

  // --- 11. Напитки ---
  { slug: "voda", name: "Вода питьевая негаз.", group: G.beverage, unit: "ml", kcal: 0, protein: 0, fat: 0, carb: 0, fiber: 0, sodium: 5, packSize: 1500, pricePerPack: 40, shelfLifeDays: 365, allergens: [] },
  { slug: "voda-mineralnaya", name: "Вода минеральная газ.", group: G.beverage, unit: "ml", kcal: 0, protein: 0, fat: 0, carb: 0, fiber: 0, sodium: 100, packSize: 1500, pricePerPack: 50, shelfLifeDays: 365, allergens: [] },
  { slug: "sok-apelsinovyy", name: "Сок апельсиновый", group: G.beverage, unit: "ml", kcal: 47, protein: 0.7, fat: 0.2, carb: 11.0, fiber: 0.2, sodium: 5, packSize: 950, pricePerPack: 130, shelfLifeDays: 180, allergens: [] },
  { slug: "sok-yablochnyy", name: "Сок яблочный", group: G.beverage, unit: "ml", kcal: 46, protein: 0.1, fat: 0.1, carb: 11.2, fiber: 0.2, sodium: 5, packSize: 950, pricePerPack: 110, shelfLifeDays: 180, allergens: [] },
  { slug: "sok-tomatnyy", name: "Сок томатный", group: G.beverage, unit: "ml", kcal: 21, protein: 1.0, fat: 0.1, carb: 4.2, fiber: 0.7, sodium: 200, packSize: 950, pricePerPack: 110, shelfLifeDays: 180, allergens: [] },
  { slug: "nektar", name: "Нектар мультифрукт", group: G.beverage, unit: "ml", kcal: 52, protein: 0.3, fat: 0, carb: 12.5, fiber: 0.2, sodium: 5, packSize: 950, pricePerPack: 100, shelfLifeDays: 180, allergens: [] },
  { slug: "kola", name: "Кола газированная", group: G.beverage, unit: "ml", kcal: 42, protein: 0, fat: 0, carb: 10.6, fiber: 0, sodium: 10, packSize: 1500, pricePerPack: 100, shelfLifeDays: 180, allergens: [] },
  { slug: "chay-listovoy", name: "Чай чёрный листовой", group: G.beverage, unit: "g", kcal: 0, protein: 0, fat: 0, carb: 0, fiber: 0, sodium: 3, packSize: 100, pricePerPack: 130, shelfLifeDays: 730, allergens: [] },
  { slug: "chay-paketiki", name: "Чай в пакетиках", group: G.beverage, unit: "g", kcal: 0, protein: 0, fat: 0, carb: 0, fiber: 0, sodium: 3, packSize: 50, pricePerPack: 90, shelfLifeDays: 730, allergens: [] },
  { slug: "kofe-molotyy", name: "Кофе молотый", group: G.beverage, unit: "g", kcal: 200, protein: 14.0, fat: 15.0, carb: 4.0, fiber: 0, sodium: 5, packSize: 250, pricePerPack: 300, shelfLifeDays: 365, allergens: [] },
  { slug: "kofe-rastvorimyy", name: "Кофе растворимый", group: G.beverage, unit: "g", kcal: 241, protein: 15.0, fat: 3.5, carb: 41.0, fiber: 0, sodium: 40, packSize: 95, pricePerPack: 250, shelfLifeDays: 730, allergens: [] },
  { slug: "kakao-napitok", name: "Какао-напиток раствор.", group: G.beverage, unit: "g", kcal: 380, protein: 6.0, fat: 4.0, carb: 78.0, fiber: 2.0, sodium: 120, packSize: 375, pricePerPack: 180, shelfLifeDays: 365, allergens: ["milk"] },
  { slug: "kompot", name: "Компот / морс", group: G.beverage, unit: "ml", kcal: 55, protein: 0.1, fat: 0, carb: 13.5, fiber: 0.1, sodium: 5, packSize: 1000, pricePerPack: 90, shelfLifeDays: 180, allergens: [] },
  { slug: "kvas", name: "Квас", group: G.beverage, unit: "ml", kcal: 27, protein: 0.2, fat: 0, carb: 5.2, fiber: 0, sodium: 40, packSize: 1500, pricePerPack: 80, shelfLifeDays: 60, allergens: ["gluten"] },
  { slug: "moloko-ovsyanoe", name: "Молоко растит. (овсяное)", group: G.beverage, unit: "ml", kcal: 45, protein: 1.0, fat: 1.5, carb: 6.5, fiber: 0.8, sodium: 40, packSize: 1000, pricePerPack: 150, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "moloko-soevoe", name: "Молоко растит. (соевое)", group: G.beverage, unit: "ml", kcal: 54, protein: 3.3, fat: 1.8, carb: 6.0, fiber: 0.6, sodium: 40, packSize: 1000, pricePerPack: 160, shelfLifeDays: 180, allergens: ["soy"] },

  // --- 12. Консервы ---
  { slug: "tunec-konserv", name: "Тунец консерв. в с/соку", group: G.canned, unit: "g", kcal: 96, protein: 21.0, fat: 1.0, carb: 0, fiber: 0, sodium: 320, packSize: 185, pricePerPack: 150, shelfLifeDays: 1080, allergens: ["fish"] },
  { slug: "sardina-konserv", name: "Сайра / сардина в масле", group: G.canned, unit: "g", kcal: 220, protein: 18.0, fat: 16.0, carb: 0, fiber: 0, sodium: 400, packSize: 240, pricePerPack: 130, shelfLifeDays: 1080, allergens: ["fish"] },
  { slug: "shproty", name: "Шпроты в масле", group: G.canned, unit: "g", kcal: 363, protein: 17.4, fat: 32.4, carb: 0.4, fiber: 0, sodium: 500, packSize: 160, pricePerPack: 140, shelfLifeDays: 1080, allergens: ["fish"] },
  { slug: "gorbusha-konserv", name: "Горбуша натуральная", group: G.canned, unit: "g", kcal: 138, protein: 20.9, fat: 5.8, carb: 0, fiber: 0, sodium: 380, packSize: 245, pricePerPack: 200, shelfLifeDays: 1080, allergens: ["fish"] },
  { slug: "pechen-treski", name: "Печень трески", group: G.canned, unit: "g", kcal: 613, protein: 4.2, fat: 65.7, carb: 1.2, fiber: 0, sodium: 350, packSize: 190, pricePerPack: 250, shelfLifeDays: 720, allergens: ["fish"] },
  { slug: "kukuruza-konserv", name: "Кукуруза консерв.", group: G.canned, unit: "g", kcal: 58, protein: 2.2, fat: 0.4, carb: 11.2, fiber: 2.0, sodium: 270, packSize: 340, pricePerPack: 90, shelfLifeDays: 1080, allergens: [] },
  { slug: "goroshek", name: "Горошек зелёный консерв.", group: G.canned, unit: "g", kcal: 55, protein: 3.6, fat: 0.2, carb: 9.8, fiber: 3.5, sodium: 250, packSize: 400, pricePerPack: 80, shelfLifeDays: 1080, allergens: [] },
  { slug: "fasol-konserv", name: "Фасоль консерв. в с/соусе", group: G.canned, unit: "g", kcal: 99, protein: 6.7, fat: 0.5, carb: 17.0, fiber: 5.0, sodium: 350, packSize: 400, pricePerPack: 90, shelfLifeDays: 720, allergens: [] },
  { slug: "olivki", name: "Оливки/маслины консерв.", group: G.canned, unit: "g", kcal: 145, protein: 1.0, fat: 15.3, carb: 3.8, fiber: 3.0, sodium: 900, packSize: 300, pricePerPack: 130, shelfLifeDays: 720, allergens: [] },
  { slug: "tomaty-konserv", name: "Томаты в с/соку", group: G.canned, unit: "g", kcal: 21, protein: 1.1, fat: 0.2, carb: 3.8, fiber: 1.0, sodium: 180, packSize: 400, pricePerPack: 90, shelfLifeDays: 720, allergens: [] },
  { slug: "tushenka", name: "Тушёнка говяжья", group: G.canned, unit: "g", kcal: 220, protein: 15.0, fat: 17.0, carb: 0, fiber: 0, sodium: 500, packSize: 325, pricePerPack: 250, shelfLifeDays: 1080, allergens: ["meat"] },
  { slug: "pashtet", name: "Паштет печёночный", group: G.canned, unit: "g", kcal: 315, protein: 11.0, fat: 28.0, carb: 4.0, fiber: 0, sodium: 600, packSize: 100, pricePerPack: 70, shelfLifeDays: 720, allergens: ["meat"] },

  // --- 13. Замороженное ---
  { slug: "pelmeni", name: "Пельмени", group: G.frozen, unit: "g", kcal: 275, protein: 12.0, fat: 15.0, carb: 24.0, fiber: 1.5, sodium: 450, packSize: 800, pricePerPack: 280, shelfLifeDays: 180, allergens: ["gluten", "meat", "egg"] },
  { slug: "vareniki", name: "Вареники с картофелем", group: G.frozen, unit: "g", kcal: 190, protein: 5.0, fat: 4.0, carb: 33.0, fiber: 2.0, sodium: 350, packSize: 800, pricePerPack: 180, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "blinchiki", name: "Блинчики с мясом", group: G.frozen, unit: "g", kcal: 232, protein: 8.0, fat: 10.0, carb: 27.0, fiber: 1.0, sodium: 400, packSize: 420, pricePerPack: 160, shelfLifeDays: 180, allergens: ["gluten", "meat", "egg", "milk"] },
  { slug: "smes-ovoshchnaya", name: "Смесь овощная (мексиканская)", group: G.frozen, unit: "g", kcal: 65, protein: 2.5, fat: 0.4, carb: 12.5, fiber: 3.0, sodium: 20, packSize: 400, pricePerPack: 110, shelfLifeDays: 365, allergens: [] },
  { slug: "brokkoli-zam", name: "Брокколи заморож.", group: G.frozen, unit: "g", kcal: 34, protein: 2.8, fat: 0.4, carb: 4.0, fiber: 2.6, sodium: 25, packSize: 400, pricePerPack: 130, shelfLifeDays: 365, allergens: [] },
  { slug: "cvetnaya-zam", name: "Цветная капуста заморож.", group: G.frozen, unit: "g", kcal: 30, protein: 2.5, fat: 0.3, carb: 4.2, fiber: 2.1, sodium: 15, packSize: 400, pricePerPack: 110, shelfLifeDays: 365, allergens: [] },
  { slug: "yagodnaya-smes", name: "Ягодная смесь заморож.", group: G.frozen, unit: "g", kcal: 44, protein: 0.8, fat: 0.4, carb: 8.5, fiber: 3.0, sodium: 2, packSize: 300, pricePerPack: 200, shelfLifeDays: 365, allergens: [] },
  { slug: "kartofel-fri", name: "Картофель фри заморож.", group: G.frozen, unit: "g", kcal: 155, protein: 2.5, fat: 5.0, carb: 24.0, fiber: 2.5, sodium: 30, packSize: 750, pricePerPack: 150, shelfLifeDays: 365, allergens: [] },
  { slug: "kotlety", name: "Котлеты полуфабрикат", group: G.frozen, unit: "g", kcal: 250, protein: 12.0, fat: 18.0, carb: 10.0, fiber: 0.5, sodium: 500, packSize: 450, pricePerPack: 220, shelfLifeDays: 180, allergens: ["meat", "gluten", "egg"] },
  { slug: "naggetsy", name: "Наггетсы куриные", group: G.frozen, unit: "g", kcal: 260, protein: 14.0, fat: 15.0, carb: 17.0, fiber: 1.0, sodium: 550, packSize: 300, pricePerPack: 200, shelfLifeDays: 180, allergens: ["poultry", "gluten", "egg"] },
  { slug: "rybnye-palochki", name: "Рыбные палочки", group: G.frozen, unit: "g", kcal: 200, protein: 10.0, fat: 8.5, carb: 20.0, fiber: 1.0, sodium: 400, packSize: 300, pricePerPack: 180, shelfLifeDays: 180, allergens: ["fish", "gluten"] },
  { slug: "testo-sloenoe", name: "Тесто слоёное", group: G.frozen, unit: "g", kcal: 336, protein: 6.0, fat: 21.0, carb: 31.0, fiber: 1.5, sodium: 300, packSize: 500, pricePerPack: 150, shelfLifeDays: 180, allergens: ["gluten"] },
  { slug: "morozhenoe-eskimo", name: "Мороженое эскимо", group: G.frozen, unit: "g", kcal: 270, protein: 3.8, fat: 18.0, carb: 23.0, fiber: 0, sodium: 60, packSize: 200, pricePerPack: 180, shelfLifeDays: 180, allergens: ["milk"] },
  { slug: "hinkali", name: "Хинкали заморож.", group: G.frozen, unit: "g", kcal: 235, protein: 10.0, fat: 11.0, carb: 24.0, fiber: 1.5, sodium: 420, packSize: 900, pricePerPack: 320, shelfLifeDays: 180, allergens: ["gluten", "meat"] },
];

export const RECIPES: SeedRecipe[] = [
  {
    slug: "ovsyanka-banan",
    name: "Овсянка на молоке с бананом",
    steps: [
      "Довести молоко до кипения, всыпать хлопья, помешивать.",
      "Варить 5–7 минут на слабом огне до загустения.",
      "Снять с огня, добавить нарезанный банан и мёд.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "ovsyanka", grams: 60 },
      { ingredient: "moloko", grams: 200 },
      { ingredient: "banany", grams: 100 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "tvorog-banan-orehi",
    name: "Творог с бананом и грецким орехом",
    steps: [
      "Размять творог вилкой.",
      "Добавить нарезанный банан, орехи и мёд, перемешать.",
    ],
    timeMin: 5,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast", "snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "tvorog5", grams: 200 },
      { ingredient: "banany", grams: 80 },
      { ingredient: "greckiy-orekh", grams: 15 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "yaichnica-ovoshchi",
    name: "Яичница с овощами",
    steps: [
      "Разогреть масло на сковороде, обжарить нарезанный перец 3 минуты.",
      "Добавить помидоры, готовить ещё 2 минуты.",
      "Влить взбитые яйца, посолить, довести до готовности под крышкой.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "yaytso", grams: 110 },
      { ingredient: "pomidory", grams: 100 },
      { ingredient: "perec", grams: 50 },
      { ingredient: "maslo-podsolnechnoe", grams: 5 },
      { ingredient: "sol", grams: 1 },
    ],
  },
  {
    slug: "omlet-syr",
    name: "Омлет с сыром",
    steps: [
      "Взбить яйца с молоком и солью.",
      "Вылить на разогретую сковороду со сливочным маслом.",
      "Посыпать тёртым сыром, готовить под крышкой до схватывания.",
    ],
    timeMin: 10,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "yaytso", grams: 165 },
      { ingredient: "moloko", grams: 50 },
      { ingredient: "syr", grams: 40 },
      { ingredient: "maslo-slivochnoe", grams: 5 },
      { ingredient: "sol", grams: 1 },
    ],
  },
  {
    slug: "grechka-yabloko",
    name: "Гречневая каша с яблоком",
    steps: [
      "Промыть гречку, залить водой 1:2, довести до кипения.",
      "Варить под крышкой 15 минут до впитывания воды.",
      "Вмешать натёртое яблоко и мёд.",
    ],
    timeMin: 20,
    difficulty: 1,
    servings: 2,
    slots: ["breakfast"],
    // Не веганское: содержит мёд.
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "grechka", grams: 150 },
      { ingredient: "yabloki", grams: 150 },
      { ingredient: "med", grams: 20 },
    ],
  },
  {
    slug: "tost-yaytso",
    name: "Тост цельнозерновой с яйцом",
    steps: [
      "Отварить яйцо вкрутую, очистить и нарезать.",
      "Подсушить хлеб, выложить листья салата и помидор.",
      "Сверху разложить яйцо, посолить.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast", "snack"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "hleb-cz", grams: 80 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "pomidory", grams: 60 },
      { ingredient: "salat", grams: 20 },
    ],
  },
  {
    slug: "yogurt-banan-orehi",
    name: "Йогурт с бананом и орехами",
    steps: ["Нарезать банан.", "Смешать йогурт с бананом, орехами и мёдом."],
    timeMin: 4,
    difficulty: 1,
    servings: 1,
    slots: ["snack", "breakfast"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "yogurt", grams: 200 },
      { ingredient: "banany", grams: 100 },
      { ingredient: "greckiy-orekh", grams: 15 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "sup-kurinyy",
    name: "Куриный суп с лапшой",
    steps: [
      "Отварить куриное филе 20 минут, вынуть и нарезать.",
      "В бульон добавить картофель кубиками, варить 10 минут.",
      "Спассеровать лук и морковь на масле, добавить в суп.",
      "Всыпать макароны, вернуть курицу, варить 8 минут.",
      "Посолить, добавить зелень, дать настояться.",
    ],
    timeMin: 45,
    difficulty: 2,
    servings: 4,
    slots: ["lunch"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kur-file", grams: 400 },
      { ingredient: "kartofel", grams: 300 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "makarony", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
      { ingredient: "zelen", grams: 20 },
      { ingredient: "sol", grams: 4 },
    ],
  },
  {
    slug: "shchi-govyadina",
    name: "Щи из свежей капусты с говядиной",
    steps: [
      "Отварить говядину до готовности, нарезать, бульон сохранить.",
      "Добавить в бульон картофель, варить 10 минут.",
      "Спассеровать лук, морковь и томатную пасту, добавить в кастрюлю.",
      "Всыпать нашинкованную капусту, вернуть мясо, варить 15 минут.",
      "Посолить по вкусу.",
    ],
    timeMin: 70,
    difficulty: 2,
    servings: 4,
    slots: ["lunch"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "govyadina", grams: 400 },
      { ingredient: "kapusta", grams: 300 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "tomat-pasta", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
      { ingredient: "sol", grams: 4 },
    ],
  },
  {
    slug: "sup-chechevica",
    name: "Чечевичный суп",
    steps: [
      "Промыть чечевицу, залить водой, довести до кипения.",
      "Добавить картофель, варить 15 минут.",
      "Спассеровать лук, морковь и томатную пасту, добавить в суп.",
      "Варить до мягкости чечевицы, посолить.",
    ],
    timeMin: 40,
    difficulty: 2,
    servings: 3,
    slots: ["lunch"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "chechevica", grams: 200 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "tomat-pasta", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
      { ingredient: "sol", grams: 3 },
    ],
  },
  {
    slug: "grechka-kurica",
    name: "Гречка с куриным бедром и овощами",
    steps: [
      "Отварить гречку до готовности.",
      "Обжарить куриное бедро на масле до румяности.",
      "Добавить лук и морковь, тушить 10 минут.",
      "Подавать курицу с овощами на гречке.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "grechka", grams: 150 },
      { ingredient: "kur-bedro", grams: 300 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "maslo-podsolnechnoe", grams: 10 },
    ],
  },
  {
    slug: "ris-ryba",
    name: "Рис с минтаем и овощами",
    steps: [
      "Отварить рис до готовности.",
      "Припустить минтай с луком и морковью на масле под крышкой 15 минут.",
      "Подавать рыбу с овощами на рисе.",
    ],
    timeMin: 30,
    difficulty: 2,
    servings: 2,
    slots: ["dinner", "lunch"],
    diet: ["pescatarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "ris-kruglyy", grams: 150 },
      { ingredient: "mintay", grams: 300 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "maslo-podsolnechnoe", grams: 10 },
    ],
  },
  {
    slug: "pasta-bolognese",
    name: "Паста с фаршем по-болонски",
    steps: [
      "Отварить макароны до состояния аль денте.",
      "Обжарить лук и морковь на оливковом масле.",
      "Добавить фарш, обжарить до румяности.",
      "Влить томатную пасту с водой, тушить 15 минут, посолить.",
      "Смешать соус с макаронами.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "makarony", grams: 250 },
      { ingredient: "farsh-govyazhiy", grams: 300 },
      { ingredient: "tomat-pasta", grams: 80 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "maslo-olivkovoe", grams: 15 },
    ],
  },
  {
    slug: "kapusta-tushenaya-kurica",
    name: "Тушёная капуста с курицей",
    steps: [
      "Нашинковать капусту, нарезать куриное филе.",
      "Обжарить курицу на масле, добавить лук и морковь.",
      "Добавить капусту и томатную пасту, тушить под крышкой 25 минут.",
      "Посолить по вкусу.",
    ],
    timeMin: 40,
    difficulty: 2,
    servings: 3,
    slots: ["dinner", "lunch"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kapusta", grams: 500 },
      { ingredient: "kur-file", grams: 400 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "tomat-pasta", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "ovoshchnoe-ragu",
    name: "Овощное рагу с кабачком",
    steps: [
      "Нарезать все овощи кубиками.",
      "Обжарить лук и морковь на масле.",
      "Добавить картофель, кабачок, перец и помидоры.",
      "Тушить под крышкой 25 минут, посолить.",
    ],
    timeMin: 40,
    difficulty: 1,
    servings: 3,
    slots: ["dinner", "lunch"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "kabachok", grams: 300 },
      { ingredient: "kartofel", grams: 300 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "pomidory", grams: 200 },
      { ingredient: "perec", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 20 },
    ],
  },
  {
    slug: "kurica-grill-brokkoli",
    name: "Куриная грудка с брокколи",
    steps: [
      "Нарезать филе, обжарить на оливковом масле с чесноком.",
      "Отварить или приготовить на пару брокколи 5–7 минут.",
      "Подавать курицу с брокколи, посолить.",
    ],
    timeMin: 25,
    difficulty: 1,
    servings: 2,
    slots: ["dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kur-file", grams: 400 },
      { ingredient: "brokkoli", grams: 300 },
      { ingredient: "maslo-olivkovoe", grams: 15 },
      { ingredient: "chesnok", grams: 10 },
    ],
  },
  {
    slug: "ryba-tushenaya-ovoshchi",
    name: "Тушёная горбуша с овощами",
    steps: [
      "Нарезать горбушу порционно.",
      "Выложить в сотейник с луком, морковью и картофелем.",
      "Добавить немного воды и масло, тушить под крышкой 25 минут.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 2,
    slots: ["dinner"],
    diet: ["pescatarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "gorbusha", grams: 300 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "maslo-podsolnechnoe", grams: 10 },
    ],
  },
  {
    slug: "salat-ovoshchi-syr",
    name: "Овощной салат с сыром",
    steps: [
      "Нарезать помидоры, огурцы и перец.",
      "Порвать листья салата, добавить кубики сыра.",
      "Заправить оливковым маслом, посолить.",
    ],
    timeMin: 10,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "pomidory", grams: 200 },
      { ingredient: "ogurcy", grams: 200 },
      { ingredient: "perec", grams: 100 },
      { ingredient: "salat", grams: 60 },
      { ingredient: "syr", grams: 60 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
    ],
  },

  // ─── Полное наполнение (тикет 21): завтраки ──────────────────────────────────
  {
    slug: "syrniki",
    name: "Сырники из творога",
    steps: [
      "Смешать творог, яйцо, муку и сахар в однородное тесто.",
      "Сформовать сырники, обвалять в муке.",
      "Обжарить на масле по 3–4 минуты с каждой стороны.",
    ],
    timeMin: 20,
    difficulty: 2,
    servings: 2,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "tvorog9", grams: 250 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "muka", grams: 40 },
      { ingredient: "sahar", grams: 15 },
      { ingredient: "maslo-podsolnechnoe", grams: 10 },
    ],
  },
  {
    slug: "omlet-shpinat",
    name: "Омлет со шпинатом",
    steps: [
      "Взбить яйца с молоком и солью.",
      "Припустить шпинат на сливочном масле 1–2 минуты.",
      "Влить яйца, готовить под крышкой до схватывания.",
    ],
    timeMin: 10,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "yaytso", grams: 165 },
      { ingredient: "shpinat", grams: 60 },
      { ingredient: "moloko", grams: 40 },
      { ingredient: "maslo-slivochnoe", grams: 5 },
      { ingredient: "sol", grams: 1 },
    ],
  },
  {
    slug: "kasha-pshennaya-tykva",
    name: "Пшённая каша с тыквой",
    steps: [
      "Нарезать тыкву кубиками, припустить в молоке 10 минут.",
      "Всыпать промытое пшено, варить на слабом огне 20 минут.",
      "Заправить сливочным маслом и сахаром.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "psheno", grams: 80 },
      { ingredient: "moloko", grams: 200 },
      { ingredient: "tykva", grams: 150 },
      { ingredient: "maslo-slivochnoe", grams: 10 },
      { ingredient: "sahar", grams: 10 },
    ],
  },
  {
    slug: "tvorog-yagody",
    name: "Творог с ягодами и мёдом",
    steps: ["Разморозить ягоды.", "Смешать творог с ягодами и мёдом."],
    timeMin: 5,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast", "snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "tvorog5", grams: 200 },
      { ingredient: "yagodnaya-smes", grams: 80 },
      { ingredient: "med", grams: 15 },
    ],
  },
  {
    slug: "ovsyanoblin",
    name: "Овсяноблин с сыром",
    steps: [
      "Смолоть хлопья, смешать с яйцом и молоком в тесто.",
      "Вылить на сковороду, обжарить с двух сторон.",
      "Выложить сыр на половину, сложить и прогреть.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove", "blender"],
    items: [
      { ingredient: "ovsyanka", grams: 50 },
      { ingredient: "yaytso", grams: 110 },
      { ingredient: "moloko", grams: 30 },
      { ingredient: "syr", grams: 30 },
    ],
  },
  {
    slug: "kasha-risovaya-moloko",
    name: "Рисовая каша на молоке",
    steps: [
      "Промыть рис, залить молоком, довести до кипения.",
      "Варить на слабом огне 20 минут, помешивая.",
      "Добавить сахар и сливочное масло.",
    ],
    timeMin: 25,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "ris-kruglyy", grams: 70 },
      { ingredient: "moloko", grams: 250 },
      { ingredient: "sahar", grams: 10 },
      { ingredient: "maslo-slivochnoe", grams: 10 },
    ],
  },
  {
    slug: "tost-avokado-yaytso",
    name: "Тост с авокадо и яйцом",
    steps: [
      "Отварить яйцо, размять авокадо с солью.",
      "Подсушить хлеб, намазать авокадо.",
      "Сверху выложить нарезанное яйцо.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast", "snack"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "hleb-cz", grams: 60 },
      { ingredient: "avokado", grams: 70 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "sol", grams: 1 },
    ],
  },
  {
    slug: "zapekanka-tvorog",
    name: "Творожная запеканка",
    steps: [
      "Смешать творог с яйцом, манкой и сахаром.",
      "Выложить в форму, разровнять.",
      "Запекать при 180 °C 30 минут до румяной корочки.",
    ],
    timeMin: 45,
    difficulty: 2,
    servings: 2,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["oven"],
    items: [
      { ingredient: "tvorog5", grams: 300 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "manka", grams: 40 },
      { ingredient: "sahar", grams: 20 },
    ],
  },
  {
    slug: "grechka-moloko",
    name: "Гречневая каша на молоке",
    steps: [
      "Отварить гречку до готовности.",
      "Залить горячим молоком, добавить масло, прогреть.",
    ],
    timeMin: 20,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "grechka", grams: 80 },
      { ingredient: "moloko", grams: 200 },
      { ingredient: "maslo-slivochnoe", grams: 10 },
    ],
  },
  {
    slug: "smuzi-banan-oves",
    name: "Смузи банан-овсянка на кефире",
    steps: ["Сложить все продукты в блендер.", "Взбить до однородности."],
    timeMin: 5,
    difficulty: 1,
    servings: 1,
    slots: ["breakfast", "snack"],
    diet: ["vegetarian"],
    equipment: ["blender"],
    items: [
      { ingredient: "kefir", grams: 250 },
      { ingredient: "banany", grams: 120 },
      { ingredient: "ovsyanka", grams: 30 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "bliny-tvorog",
    name: "Блины с творогом",
    steps: [
      "Смешать муку, молоко и яйцо в жидкое тесто.",
      "Испечь тонкие блины на масле.",
      "Завернуть творог, смешанный с сахаром.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 3,
    slots: ["breakfast"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "muka", grams: 120 },
      { ingredient: "moloko", grams: 250 },
      { ingredient: "yaytso", grams: 110 },
      { ingredient: "tvorog5", grams: 150 },
      { ingredient: "sahar", grams: 20 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },

  // ─── Перекусы ────────────────────────────────────────────────────────────────
  {
    slug: "yabloko-orehi",
    name: "Яблоко с грецким орехом",
    steps: ["Нарезать яблоко дольками.", "Подать с ядрами грецкого ореха."],
    timeMin: 3,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegan", "vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "yabloki", grams: 150 },
      { ingredient: "greckiy-orekh", grams: 25 },
    ],
  },
  {
    slug: "banan-arahisovaya-pasta",
    name: "Банан с арахисовой пастой",
    steps: ["Нарезать банан.", "Подать с арахисовой пастой."],
    timeMin: 3,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegan", "vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "banany", grams: 120 },
      { ingredient: "arahisovaya-pasta", grams: 25 },
    ],
  },
  {
    slug: "orehovyy-miks",
    name: "Ореховый микс",
    steps: ["Смешать миндаль и фундук."],
    timeMin: 2,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegan", "vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "mindal", grams: 25 },
      { ingredient: "funduk", grams: 25 },
    ],
  },
  {
    slug: "hlebcy-syr-tvorozhnyy",
    name: "Хлебцы с творожным сыром",
    steps: ["Намазать хлебцы творожным сыром.", "Сверху выложить кружок помидора."],
    timeMin: 4,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "hlebcy", grams: 30 },
      { ingredient: "syr-tvorozhnyy", grams: 40 },
      { ingredient: "pomidory", grams: 50 },
    ],
  },
  {
    slug: "tvorog-oreh-med",
    name: "Творог с орехами и мёдом",
    steps: ["Смешать творог с рублеными орехами и мёдом."],
    timeMin: 4,
    difficulty: 1,
    servings: 1,
    slots: ["snack", "breakfast"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "tvorog5", grams: 180 },
      { ingredient: "greckiy-orekh", grams: 15 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "smuzi-yagody-yogurt",
    name: "Ягодный смузи на йогурте",
    steps: ["Сложить продукты в блендер.", "Взбить до однородности."],
    timeMin: 5,
    difficulty: 1,
    servings: 1,
    slots: ["snack", "breakfast"],
    diet: ["vegetarian"],
    equipment: ["blender"],
    items: [
      { ingredient: "yogurt", grams: 200 },
      { ingredient: "yagodnaya-smes", grams: 100 },
      { ingredient: "banany", grams: 80 },
      { ingredient: "med", grams: 10 },
    ],
  },
  {
    slug: "kefir-hlebcy",
    name: "Кефир с хлебцами",
    steps: ["Подать стакан кефира с ржаными хлебцами."],
    timeMin: 2,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "kefir", grams: 250 },
      { ingredient: "hlebcy", grams: 30 },
    ],
  },
  {
    slug: "yaytsa-ogurec",
    name: "Яйца вкрутую с огурцом",
    steps: ["Отварить яйца вкрутую.", "Подать с нарезанным огурцом, посолить."],
    timeMin: 12,
    difficulty: 1,
    servings: 1,
    slots: ["snack"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "yaytso", grams: 110 },
      { ingredient: "ogurcy", grams: 100 },
      { ingredient: "sol", grams: 1 },
    ],
  },

  // ─── Обеды и ужины ───────────────────────────────────────────────────────────
  {
    slug: "plov-kurica",
    name: "Плов с курицей",
    steps: [
      "Обжарить куриное бедро на масле до румяности.",
      "Добавить лук и морковь соломкой, пассеровать.",
      "Всыпать рис, залить водой, добавить чеснок.",
      "Готовить под крышкой на слабом огне 25 минут.",
    ],
    timeMin: 60,
    difficulty: 2,
    servings: 4,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "ris-dlinnozernyy", grams: 200 },
      { ingredient: "kur-bedro", grams: 300 },
      { ingredient: "morkov", grams: 150 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 25 },
      { ingredient: "chesnok", grams: 10 },
    ],
  },
  {
    slug: "gulyash-grechka",
    name: "Говяжий гуляш с гречкой",
    steps: [
      "Обжарить нарезанную говядину.",
      "Добавить лук, морковь и томатную пасту, тушить 40 минут.",
      "Подавать с отварной гречкой.",
    ],
    timeMin: 60,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "grechka", grams: 200 },
      { ingredient: "govyadina", grams: 400 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "tomat-pasta", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "kotlety-indeyka-pyure",
    name: "Котлеты из индейки с пюре",
    steps: [
      "Смешать фарш с яйцом и тёртым луком, сформовать котлеты.",
      "Обжарить котлеты до готовности.",
      "Отварить картофель, растолочь с молоком и маслом.",
    ],
    timeMin: 45,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "farsh-indeyka", grams: 400 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "kartofel", grams: 500 },
      { ingredient: "moloko", grams: 100 },
      { ingredient: "maslo-slivochnoe", grams: 20 },
    ],
  },
  {
    slug: "treska-zapechennaya",
    name: "Треска, запечённая с овощами",
    steps: [
      "Выложить филе трески в форму с кабачком, помидорами и луком.",
      "Сбрызнуть оливковым маслом, посолить.",
      "Запекать при 200 °C 25 минут.",
    ],
    timeMin: 35,
    difficulty: 1,
    servings: 2,
    slots: ["dinner", "lunch"],
    diet: ["pescatarian"],
    equipment: ["oven"],
    items: [
      { ingredient: "treska", grams: 400 },
      { ingredient: "kabachok", grams: 200 },
      { ingredient: "pomidory", grams: 150 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
    ],
  },
  {
    slug: "fasol-tushenaya-ovoshchi",
    name: "Тушёная фасоль с овощами",
    steps: [
      "Замочить и отварить фасоль до мягкости.",
      "Спассеровать лук и морковь, добавить помидоры.",
      "Соединить с фасолью, тушить 15 минут, посолить.",
    ],
    timeMin: 90,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "fasol", grams: 200 },
      { ingredient: "pomidory", grams: 200 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 20 },
    ],
  },
  {
    slug: "kinoa-ovoshchi",
    name: "Киноа с овощами",
    steps: [
      "Отварить киноа 15 минут.",
      "Обжарить кабачок, перец и лук на оливковом масле.",
      "Добавить помидоры, соединить с киноа, посолить.",
    ],
    timeMin: 30,
    difficulty: 2,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "kinoa", grams: 150 },
      { ingredient: "kabachok", grams: 150 },
      { ingredient: "perec", grams: 100 },
      { ingredient: "pomidory", grams: 150 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
    ],
  },
  {
    slug: "makarony-syr",
    name: "Паста с сыром",
    steps: [
      "Отварить спагетти аль денте.",
      "Растопить сыр в горячем молоке со сливочным маслом.",
      "Соединить соус с пастой.",
    ],
    timeMin: 20,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: ["vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "spagetti", grams: 200 },
      { ingredient: "syr", grams: 80 },
      { ingredient: "moloko", grams: 150 },
      { ingredient: "maslo-slivochnoe", grams: 20 },
    ],
  },
  {
    slug: "sup-gorohovyy",
    name: "Гороховый суп",
    steps: [
      "Отварить горох до мягкости.",
      "Добавить картофель, варить 15 минут.",
      "Спассеровать лук и морковь, добавить в суп, посолить.",
    ],
    timeMin: 70,
    difficulty: 2,
    servings: 4,
    slots: ["lunch"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "goroh", grams: 200 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "borsch",
    name: "Борщ с говядиной",
    steps: [
      "Отварить говядину, нарезать, бульон сохранить.",
      "Добавить картофель и капусту, варить 15 минут.",
      "Спассеровать свёклу, морковь, лук с томатной пастой.",
      "Соединить всё, вернуть мясо, варить 10 минут.",
    ],
    timeMin: 90,
    difficulty: 3,
    servings: 5,
    slots: ["lunch"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "govyadina", grams: 400 },
      { ingredient: "svekla", grams: 300 },
      { ingredient: "kapusta", grams: 200 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "tomat-pasta", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "uha-gorbusha",
    name: "Уха из горбуши",
    steps: [
      "Отварить картофель и морковь 10 минут.",
      "Добавить нарезанную горбушу и лук, варить 15 минут.",
      "Посолить, добавить зелень, дать настояться.",
    ],
    timeMin: 40,
    difficulty: 2,
    servings: 4,
    slots: ["lunch"],
    diet: ["pescatarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "gorbusha", grams: 400 },
      { ingredient: "kartofel", grams: 300 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "zelen", grams: 20 },
    ],
  },
  {
    slug: "tefteli-ris",
    name: "Тефтели с рисом в томатном соусе",
    steps: [
      "Смешать фарш с отваренным рисом и луком, сформовать тефтели.",
      "Обжарить, залить томатным соусом с водой.",
      "Тушить под крышкой 25 минут.",
    ],
    timeMin: 45,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "farsh-govyazhiy", grams: 300 },
      { ingredient: "ris-kruglyy", grams: 60 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "tomat-pasta", grams: 60 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "zapekanka-kartofel-farsh",
    name: "Картофельная запеканка с фаршем",
    steps: [
      "Отварить картофель, растолочь с молоком.",
      "Обжарить фарш с луком.",
      "Собрать слоями, посыпать сыром, запечь при 190 °C 25 минут.",
    ],
    timeMin: 60,
    difficulty: 2,
    servings: 4,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["oven", "stove"],
    items: [
      { ingredient: "kartofel", grams: 600 },
      { ingredient: "farsh-govyazhiy", grams: 300 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "moloko", grams: 100 },
      { ingredient: "syr", grams: 50 },
      { ingredient: "maslo-slivochnoe", grams: 20 },
    ],
  },
  {
    slug: "salat-tunec-fasol",
    name: "Салат с тунцом и фасолью",
    steps: [
      "Слить жидкость с тунца, фасоли и кукурузы.",
      "Смешать с нарезанным луком.",
      "Заправить оливковым маслом.",
    ],
    timeMin: 10,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "snack"],
    diet: ["pescatarian"],
    equipment: ["none"],
    items: [
      { ingredient: "tunec-konserv", grams: 185 },
      { ingredient: "fasol-konserv", grams: 200 },
      { ingredient: "kukuruza-konserv", grams: 100 },
      { ingredient: "luk", grams: 40 },
      { ingredient: "maslo-olivkovoe", grams: 15 },
    ],
  },
  {
    slug: "salat-olivie",
    name: "Салат «Оливье»",
    steps: [
      "Отварить картофель, морковь и яйца, остудить.",
      "Нарезать всё кубиком, добавить горошек и колбасу.",
      "Заправить майонезом, посолить.",
    ],
    timeMin: 40,
    difficulty: 2,
    servings: 4,
    slots: ["lunch", "snack"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kartofel", grams: 300 },
      { ingredient: "yaytso", grams: 110 },
      { ingredient: "kolbasa-varenaya", grams: 150 },
      { ingredient: "goroshek", grams: 150 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "mayonez", grams: 100 },
    ],
  },
  {
    slug: "vinegret",
    name: "Винегрет",
    steps: [
      "Отварить свёклу, картофель и морковь, остудить.",
      "Нарезать кубиком, добавить горошек и лук.",
      "Заправить подсолнечным маслом, посолить.",
    ],
    timeMin: 50,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "snack"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "svekla", grams: 200 },
      { ingredient: "kartofel", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "goroshek", grams: 100 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "maslo-podsolnechnoe", grams: 30 },
    ],
  },
  {
    slug: "grechka-griby",
    name: "Гречка с грибами и луком",
    steps: [
      "Отварить гречку.",
      "Обжарить грибы с луком на масле до румяности.",
      "Соединить с гречкой, посолить.",
    ],
    timeMin: 30,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "grechka", grams: 150 },
      { ingredient: "shampinony", grams: 200 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 20 },
    ],
  },
  {
    slug: "kapusta-griby-tushenaya",
    name: "Тушёная капуста с грибами",
    steps: [
      "Обжарить грибы с луком и морковью.",
      "Добавить нашинкованную капусту и томатную пасту.",
      "Тушить под крышкой 25 минут, посолить.",
    ],
    timeMin: 40,
    difficulty: 1,
    servings: 2,
    slots: ["dinner", "lunch"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "kapusta", grams: 500 },
      { ingredient: "shampinony", grams: 200 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "tomat-pasta", grams: 30 },
      { ingredient: "maslo-podsolnechnoe", grams: 20 },
    ],
  },
  {
    slug: "kurica-karri-ris",
    name: "Курица карри с рисом",
    steps: [
      "Обжарить курицу с луком и морковью.",
      "Влить молоко с карри, тушить 15 минут.",
      "Подавать с отварным рисом.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kur-file", grams: 400 },
      { ingredient: "ris-dlinnozernyy", grams: 150 },
      { ingredient: "moloko", grams: 100 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "zharkoe-svinina",
    name: "Жаркое по-домашнему",
    steps: [
      "Обжарить нарезанную свинину до румяности.",
      "Добавить картофель, лук, морковь и томатную пасту.",
      "Залить водой, тушить под крышкой 40 минут.",
    ],
    timeMin: 70,
    difficulty: 2,
    servings: 4,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "svinina", grams: 400 },
      { ingredient: "kartofel", grams: 500 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "tomat-pasta", grams: 30 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "golubcy-lenivye",
    name: "Ленивые голубцы",
    steps: [
      "Смешать фарш, отваренный рис, нашинкованную капусту, лук и морковь.",
      "Сформовать тефтели, обжарить.",
      "Залить томатным соусом, тушить 30 минут.",
    ],
    timeMin: 50,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kapusta", grams: 300 },
      { ingredient: "farsh-govyazhiy", grams: 300 },
      { ingredient: "ris-kruglyy", grams: 80 },
      { ingredient: "luk", grams: 80 },
      { ingredient: "morkov", grams: 80 },
      { ingredient: "tomat-pasta", grams: 40 },
    ],
  },
  {
    slug: "pasta-krevetki",
    name: "Паста с креветками",
    steps: [
      "Отварить спагетти аль денте.",
      "Обжарить креветки с чесноком на оливковом масле.",
      "Добавить помидоры, соединить с пастой.",
    ],
    timeMin: 25,
    difficulty: 2,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: ["pescatarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "spagetti", grams: 200 },
      { ingredient: "krevetki", grams: 200 },
      { ingredient: "chesnok", grams: 10 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
      { ingredient: "pomidory", grams: 100 },
    ],
  },
  {
    slug: "rybnye-kotlety-mintay",
    name: "Рыбные котлеты из минтая",
    steps: [
      "Измельчить филе минтая, смешать с яйцом и луком.",
      "Сформовать котлеты, обвалять в сухарях.",
      "Обжарить до румяной корочки.",
    ],
    timeMin: 35,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: ["pescatarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "mintay", grams: 400 },
      { ingredient: "yaytso", grams: 55 },
      { ingredient: "luk", grams: 60 },
      { ingredient: "suhari", grams: 40 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "pechen-v-smetane",
    name: "Куриная печень в сметане",
    steps: [
      "Обжарить печень 5 минут.",
      "Добавить лук и морковь, пассеровать.",
      "Влить сметану, тушить 10 минут, посолить.",
    ],
    timeMin: 30,
    difficulty: 2,
    servings: 3,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "pechen-kurinaya", grams: 400 },
      { ingredient: "luk", grams: 100 },
      { ingredient: "morkov", grams: 100 },
      { ingredient: "smetana", grams: 100 },
      { ingredient: "maslo-podsolnechnoe", grams: 15 },
    ],
  },
  {
    slug: "salat-grecheskiy",
    name: "Греческий салат",
    steps: [
      "Нарезать помидоры, огурцы и перец крупно.",
      "Добавить кубики моцареллы и маслины.",
      "Заправить оливковым маслом.",
    ],
    timeMin: 12,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "snack"],
    diet: ["vegetarian"],
    equipment: ["none"],
    items: [
      { ingredient: "pomidory", grams: 200 },
      { ingredient: "ogurcy", grams: 150 },
      { ingredient: "perec", grams: 100 },
      { ingredient: "mocarella", grams: 100 },
      { ingredient: "olivki", grams: 50 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
    ],
  },
  {
    slug: "salat-teplyy-kurica",
    name: "Тёплый салат с курицей",
    steps: [
      "Обжарить нарезанное куриное филе.",
      "Порвать салат, нарезать помидоры и огурцы.",
      "Соединить с курицей, заправить маслом, подать с хлебом.",
    ],
    timeMin: 20,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: [],
    equipment: ["stove"],
    items: [
      { ingredient: "kur-file", grams: 300 },
      { ingredient: "salat", grams: 100 },
      { ingredient: "pomidory", grams: 150 },
      { ingredient: "ogurcy", grams: 100 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
      { ingredient: "hleb-cz", grams: 60 },
    ],
  },
  {
    slug: "kuskus-ovoshchi",
    name: "Кускус с овощами",
    steps: [
      "Запарить кускус кипятком под крышкой 5 минут.",
      "Обжарить баклажан, кабачок и перец на оливковом масле.",
      "Соединить овощи с кускусом, посолить.",
    ],
    timeMin: 25,
    difficulty: 1,
    servings: 2,
    slots: ["lunch", "dinner"],
    diet: ["vegan", "vegetarian"],
    equipment: ["stove"],
    items: [
      { ingredient: "kuskus", grams: 150 },
      { ingredient: "baklazhan", grams: 150 },
      { ingredient: "kabachok", grams: 150 },
      { ingredient: "perec", grams: 100 },
      { ingredient: "maslo-olivkovoe", grams: 20 },
    ],
  },
];
